### ISSUE TITLE
Error while loading mod. 

### ISSUE THREAD

**Issue by NPC-112** [cootshk/RideableEnderPearls#1]
Im interested in using your mod, but I get the following error on my server.

My server is Minecraft 1.18.2 with Fabric Loader 0.14.14
I get this error with both the mod and the datapack version.

```

[16:53:48] [Worker-Main-1/ERROR]: Failed to load function ridablepearls:tick
--
4374 | java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 19: Incorrect argument for command at position 72: ...matches 1 <--[HERE]
4375 | at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
4376 | at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) [?:?]
4377 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
4378 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
4379 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
4380 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
4381 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
4382 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
4383 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
4384 | Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 19: Incorrect argument for command at position 72: ...matches 1 <--[HERE]
4385 | at net.minecraft.class_2158.method_9195(class_2158.java:63) ~[server-intermediary.jar:?]
4386 | at net.minecraft.class_5349.method_29451(class_5349.java:85) ~[server-intermediary.jar:?]
4387 | ... 7 more
4388 | [16:53:48] [Worker-Main-1/ERROR]: Couldn't load tag minecraft:tick as it is missing following references: ridablepearls:tick (from RideableEnderPearls)
4389 | [16:53:48] [Worker-Main-1/ERROR]: Couldn't load tag ridablepearls:tick as it is missing following references: ridablepearls:tick (from RideableEnderPearls)

```

**Comment by cootshk** [comment]
I fixed it just now, I'll make a release tomorrow when I can use my computer

**Comment by NPC-112** [comment]
I opened the jar file and replaced the data folder files with the 1.19.3 files from the repo and it worked!

thanks for the blazingly fast fix 👍
